# Site settings
title:          Emidio Torre
description:    "Developer"
url:            "https://emidiotorre.it"

# Author
author:
  name:         Emidio Torre
  url:          http://www.emidiotorre.it
  email:        emidio.torre@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
